WITH RECURSIVE TIME_CLOCK AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_CLOCK WHERE HOUR < 23
)

SELECT 
    C.HOUR,
    COUNT(O.ANIMAL_ID) AS COUNT
FROM TIME_CLOCK C
LEFT JOIN ANIMAL_OUTS O ON C.HOUR = HOUR(O.DATETIME)
GROUP BY C.HOUR
ORDER BY C.HOUR ASC;