SELECT 
    YEAR(C.DIFFERENTIATION_DATE) AS YEAR,
    (P.MAX_SIZE - C.SIZE_OF_COLONY) AS YEAR_DEV,
    C.ID
FROM ECOLI_DATA C
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) P ON YEAR(C.DIFFERENTIATION_DATE) = P.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;