SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, 
R.CONTENTS, R.CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON R.BOARD_ID = B.BOARD_ID
WHERE B.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY CREATED_DATE, TITLE