WITH FRONT_END_MASK AS (
    SELECT SUM(CODE) AS MASK
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
SKILL_PREP AS (
    SELECT 
        (SELECT MASK FROM FRONT_END_MASK) AS FE,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS PY,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS CS
)

SELECT * FROM (
    SELECT 
        CASE 
            WHEN (D.SKILL_CODE & P.FE) > 0 AND (D.SKILL_CODE & P.PY) > 0 THEN 'A'
            WHEN (D.SKILL_CODE & P.CS) > 0 THEN 'B'
            WHEN (D.SKILL_CODE & P.FE) > 0 THEN 'C'
            ELSE NULL
        END AS GRADE,
        D.ID,
        D.EMAIL
    FROM DEVELOPERS D
    CROSS JOIN SKILL_PREP P
) AS RESULT
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC;